# Change these first
owner: Joxhxh
repo: tallerGHA2

sites:
  - name: Google
    url: https://www.google.com[cite: 5]
  - name: Wikipedia
    url: https://en.wikipedia.org[cite: 5]
  - name: Hacker News
    url: https://news.ycombinator.com[cite: 5]
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co[cite: 5]
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true[cite: 5]

status-website:
  # baseUrl: /your-repo-name
  baseUrl: /tallerGHA2[cite: 5]
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg[cite: 5]
  name: Upptime[cite: 5]
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."[cite: 5]
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)[cite: 5]
  navbar:
    - title: Estado
      href: /[cite: 5]
    - title: GitHub
      href: https://github.com/Joxhxh/tallerGHA2
